#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>/Library/Logs/ch.alyaconsulting.office.templates.postinstall-$(uuidgen).log 2>&1

echo "$(date) : post installing ch.alyaconsulting.office.templates"

echo "$(date) : preparing directories"
installDir="/Library/Application Support/Microsoft"
[ -d "$installDir" ] || mkdir "$installDir"
chmod 755 "$installDir"
[ -d "$installDir/Office365" ] || mkdir "$installDir/Office365"
chmod 755 "$installDir/Office365"
[ -d "$installDir/Office365/User Content.localized" ] || mkdir "$installDir/Office365/User Content.localized"
chmod 755 "$installDir/Office365/User Content.localized"
[ -d "$installDir/Office365/User Content.localized/Templates.localized" ] || mkdir "$installDir/Office365/User Content.localized/Templates.localized"
chmod 755 "$installDir/Office365/User Content.localized/Templates.localized"
appLocation="$installDir/Office365/User Content.localized/Templates.localized"

echo "$(date) : setting file access"
find "$appLocation" -type f -exec chmod 644 {} +

echo "$(date) : cleaning old files"
if [[ -f "$appLocation/HH2023_Document_print.dotx" ]];then
    rm -f "$appLocation/HH2023_Document_print.dotx"
fi

if [[ -f "$appLocation/HH2023_Document.dotx" ]];then
    rm -f "$appLocation/HH2023_Document.dotx"
fi

if [[ -f "$appLocation/HH2023_Letter_print.dotx" ]];then
    rm -f "$appLocation/HH2023_Letter_print.dotx"
fi

if [[ -f "$appLocation/HH2023_Letter.dotx" ]];then
    rm -f "$appLocation/HH2023_Letter.dotx"
fi

echo "$(date) : done ch.alyaconsulting.office.templates.postinstall"

exit 0
