# Extraction pipeline
name: 'Nightly Extraction'

trigger:
- none

schedules:
- cron: '0 0 * * *'
  displayName: 'Nightly extraction'
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  displayName: Checkout Repo
  persistCredentials: true
  clean: true
- task: AzurePowerShell@5
  displayName: Extract Templates
  inputs:
    azureSubscription: '!!!PleaseSpecify!!!'
    ScriptType: 'FilePath'
    ScriptPath: '.\20_ExtractAll.ps1'
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'
- task: CmdLine@2
  displayName: Commit Changes
  inputs:
    script: |
      git config --global user.email "info@alyaconsulting.ch"
      git config --global user.name "Alya DevOps Pipeline"
      git checkout -b master
      git add -A
      git commit -m "Commited by pipeline [skip ci]"
      git push -u origin master
