#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>/Library/Logs/ch.alyaconsulting.teams.backgrounds.postupgrade.log 2>&1

echo "$(date) : post upgrading ch.alyaconsulting.teams.backgrounds"


runDir=$pwd
alyaDir="/Library/Alya"
logsDir="$alyaDir/Logs"
backgroundsDir="$alyaDir/TeamsBackgrounds"
agentsDir="/Library/LaunchAgents"
scriptsDir="/Library/Scripts"

echo "$(date) : preparing directories"
[ -d $alyaDir ] || mkdir $alyaDir
chmod 755 $alyaDir
[ -d $backgroundsDir ] || mkdir $backgroundsDir
chmod 755 $backgroundsDir
[ -d $logsDir ] || mkdir $logsDir
chmod 777 $logsDir

if [[ -f $scriptsDir/ch.alyaconsulting.teams.backgrounds.sh ]];then
    rm -f $scriptsDir/ch.alyaconsulting.teams.backgrounds.sh
fi

echo "$(date) : creating apply script"
cat > /tmp/ch.alyaconsulting.teams.backgrounds.tmp <<- EOF
#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>$logsDir/ch.alyaconsulting.teams.backgrounds.log 2>&1
echo "\$(date) : running ch.alyaconsulting.teams.backgrounds"
teamsDir="\$HOME/Library/Containers/com.microsoft.teams2/Data/Library/Application Support/Microsoft/MSTeams/Backgrounds/Uploads"
[ -d \$teamsDir ] || mkdir \$teamsDir
for f in $backgroundsDir/*; do
    if [[ "\$f" = *.png || "\$f" = *.PNG || "\$f" = *.jpg || "\$f" = *.JPG || "\$f" = *.gif || "\$f" = *.GIF ]]; then
        echo "Copying \$f"
        cp -f \$f \$teamsDir
    fi
done
echo "\$(date) : done ch.alyaconsulting.teams.backgrounds"
EOF

if ! cmp -s "/tmp/ch.alyaconsulting.teams.backgrounds.tmp" "$scriptsDir/ch.alyaconsulting.teams.backgrounds.sh"; then
    cp "/tmp/ch.alyaconsulting.teams.backgrounds.tmp" "$scriptsDir/ch.alyaconsulting.teams.backgrounds.sh"
fi
chmod 755 $scriptsDir/ch.alyaconsulting.teams.backgrounds.sh
xattr -d com.apple.provenance $scriptsDir/ch.alyaconsulting.teams.backgrounds.sh
xattr -d com.apple.quarantine $scriptsDir/ch.alyaconsulting.teams.backgrounds.sh
rm -f /tmp/ch.alyaconsulting.teams.backgrounds.tmp

echo "$(date) : creating login agent"
cat > /tmp/ch.alyaconsulting.teams.backgrounds.plist <<- EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" http://www.apple.com/DTDs/PropertyList-1.0.dtd>
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>ch.alyaconsulting.teams.backgrounds</string>
    <key>Program</key>
    <string>$scriptsDir/ch.alyaconsulting.teams.backgrounds.sh</string>
    <key>ProgramArguments</key>
    <array/>
    <key>WorkingDirectory</key>
    <string>$logsDir</string>
    <key>StandardOutPath</key>
    <string>$logsDir/ch.alyaconsulting.teams.backgrounds.stdout</string>
    <key>StandardErrorPath</key>
    <string>$logsDir/ch.alyaconsulting.teams.backgrounds.stderr</string>
    <key>RunAtLoad</key>
    <true/>
    <key>StartInterval</key>
    <integer>0</integer>
    <key>Nicer</key>
    <integer>1</integer>
</dict>
</plist>
EOF

if ! cmp -s "/tmp/ch.alyaconsulting.teams.backgrounds.plist" "$agentsDir/ch.alyaconsulting.teams.backgrounds.plist"; then
    cp "/tmp/ch.alyaconsulting.teams.backgrounds.plist" "$agentsDir/ch.alyaconsulting.teams.backgrounds.plist"
fi
chmod 644 $agentsDir/ch.alyaconsulting.teams.backgrounds.plist
xattr -d com.apple.provenance $agentsDir/ch.alyaconsulting.teams.backgrounds.plist
xattr -d com.apple.quarantine $agentsDir/ch.alyaconsulting.teams.backgrounds.plist
rm -f /tmp/ch.alyaconsulting.teams.backgrounds.plist

echo "$(date) : loading plist file"
launchctl load $agentsDir/ch.alyaconsulting.teams.backgrounds.plist

echo "$(date) : starting plist file"
launchctl start $agentsDir/ch.alyaconsulting.teams.backgrounds.plist

echo "$(date) : done ch.alyaconsulting.teams.backgrounds.postupgrade"

exit 0
