#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>/Library/Logs/ch.alyaconsulting.teams.backgrounds.preinstall.log 2>&1

echo "$(date) : pre installing ch.alyaconsulting.teams.backgrounds"

runDir=$pwd
alyaDir="/Library/Alya"
logsDir="$alyaDir/Logs"
backgroundsDir="$alyaDir/TeamsBackgrounds"

echo "$(date) : preparing directories"
[ -d $alyaDir ] || mkdir $alyaDir
chmod 755 $alyaDir
[ -d $backgroundsDir ] || mkdir $backgroundsDir
chmod 755 $backgroundsDir
[ -d $logsDir ] || mkdir $logsDir
chmod 777 $logsDir

echo "$(date) : done ch.alyaconsulting.teams.backgrounds.preinstall"

exit 0
