#!/bin/bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>/Library/Logs/ch.alyaconsulting.teams.backgrounds.preupgrade.log 2>&1

echo "$(date) : pre upgrading ch.alyaconsulting.teams.backgrounds"

echo "$(date) : done ch.alyaconsulting.teams.backgrounds.preupgrade"

exit 0
